% clustergramming.m

%cmap = redblue(100);

load('/Users/joechoo-choy/Downloads/ensemble/output_1.mat', 'J');

%{
accumulated_Js = J(:)';
number_of_nets = 100;

for filenumber = 2:number_of_nets
    load(sprintf('/Users/joechoo-choy/Downloads/ensemble/output_%d.mat', filenumber), 'J');
    accumulated_Js = [accumulated_Js; J(:)']; % maybe preallocate
    file = filenumber;
end

fprintf('finished with filenumber %d \n', file)
fprintf('size of accumulated Js: %d \n', size(accumulated_Js))
%}

clusters_1 = clustergram(J, 'Colormap', redbluecmap, ...
                'Cluster', 'row', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_1,'Linkage','Ward','Dendrogram',2);

clusters_2 = clustergram(J, 'Colormap', redbluecmap, ...
                'Cluster', 'column', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_2,'Linkage','Ward','Dendrogram',2);

clusters_3 = clustergram(J, 'Colormap', redbluecmap, ...
                'Cluster', 'all', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_3,'Linkage','Ward','Dendrogram',2);
